#ifndef TIMER_CONFIG_H
#define TIMER_CONFIG_H

/*
 * Choose Timer0 Mode:
 * 1. TIMER0_NORMAL_MODE
 * 2. TIMER0_PHASE_PWM_MODE
 * 3. TIMER0_CTC_MODE
 * 4. TIMER0_FAST_PWM_MODE
 */
#define TIMER0_MODE             TIMER0_NORMAL_MODE

/*
 * Choose Timer0 Prescaler:
 * TIMER0_NO_CLOCK
 * TIMER0_PRESCALER_1
 * TIMER0_PRESCALER_8
 * TIMER0_PRESCALER_64
 * TIMER0_PRESCALER_256
 * TIMER0_PRESCALER_1024
 */
#define TIMER0_PRESCALER        TIMER0_PRESCALER_64

#endif /* TIMER_CONFIG_H */
